/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/callDetails`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/jason-chat`; params?: Router.UnknownInputParams; } | { pathname: `/test-brain`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/demo` | `/demo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/recent` | `/recent`; params?: Router.UnknownInputParams; } | { pathname: `/services/callNow`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(public)'}/call/[id]` | `/call/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/callDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/jason-chat`; params?: Router.UnknownOutputParams; } | { pathname: `/test-brain`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/demo` | `/demo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/recent` | `/recent`; params?: Router.UnknownOutputParams; } | { pathname: `/services/callNow`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(public)'}/call/[id]` | `/call/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/callDetails${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/jason-chat${`?${string}` | `#${string}` | ''}` | `/test-brain${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/demo${`?${string}` | `#${string}` | ''}` | `/demo${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/recent${`?${string}` | `#${string}` | ''}` | `/recent${`?${string}` | `#${string}` | ''}` | `/services/callNow${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/callDetails`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/jason-chat`; params?: Router.UnknownInputParams; } | { pathname: `/test-brain`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/demo` | `/demo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/recent` | `/recent`; params?: Router.UnknownInputParams; } | { pathname: `/services/callNow`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/call/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/call/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(public)'}/call/[id]` | `/call/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
